services:

# *** Gestión del wokflow ***
  n8n:
    build: ./n8n_container
    container_name: n8n
    user: root
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_container/n8n_data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace

      # Cachear entornos Poetry
      - ./n8n_container/poetry_venvs:/opt/poetry-venvs
      - ./n8n_container/poetry_cache:/opt/poetry-cache
    networks:
      - net
    group_add:
      - "998"
    environment:
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - NODES_EXCLUDE=[]
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_USER_FOLDER=/home/node/.n8n
      
      # Para imports desde /workspace
      - PYTHONPATH=/workspace
      - N8N_RESTRICT_FILE_ACCESS_TO=/workspace;/root/.n8n-files

      # Para que Poetry no use .venv de Windows
      - POETRY_VIRTUALENVS_IN_PROJECT=false
      - POETRY_VIRTUALENVS_PATH=/opt/poetry-venvs
      - POETRY_CACHE_DIR=/opt/poetry-cache

  fuseki:
    image: stain/jena-fuseki
    container_name: fuseki
    ports:
      - "3030:3030"
    volumes:
      # Persistencia de Fuseki
      - ./fuseki_container/fuseki_data:/fuseki

      # Carpeta opcional para cargar TTL/RDF desde el host
      - ../outputs:/staging
    networks:
      - net
    environment:
      - ADMIN_PASSWORD=admin
      - FUSEKI_DATASET_1=kg
      - TDB=2
      - JVM_ARGS=-Xmx2g


  python_runner:
    build: ./python_container
    container_name: python_runner
    volumes:
      - ..:/workspace
      - ./python_container/poetry_venvs:/opt/poetry-venvs
      - ./python_container/poetry_cache:/opt/poetry-cache
    networks:
      - net
    environment:
      - PYTHONPATH=/workspace
      - POETRY_VIRTUALENVS_IN_PROJECT=false
      - POETRY_VIRTUALENVS_PATH=/opt/poetry-venvs
      - POETRY_CACHE_DIR=/opt/poetry-cache


  research_api:
    build:
      context: ./research_api/app
      dockerfile: Dockerfile
    container_name: research_api
    ports:
      - "8000:8000"
    environment:
      FUSEKI_QUERY_URL: "http://fuseki:3030/kg/query"
    volumes:
      - ./research_api/app:/app
    restart: unless-stopped
    
networks:
  net:
    driver: bridge
